insert into users(email, first_name, last_name, password)VALUES ('alexKras03@gmail.com', 'alex', 'krasiuk', '$2a$10$0Ye41zYMioTuj8HuWzfQ1.5CPKmSXmkNkzMg7l6E/Yw2VKTX7GdL6');
insert into users(email, first_name, last_name, password)VALUES ('alexKras04@gmail.com', 'alex', 'krasiuk', '$2a$10$0Ye41zYMioTuj8HuWzfQ1.5CPKmSXmkNkzMg7l6E/Yw2VKTX7GdL6');
insert into users(email, first_name, last_name, password)VALUES ('alexKras05@gmail.com', 'alex', 'krasiuk', '$2a$10$0Ye41zYMioTuj8HuWzfQ1.5CPKmSXmkNkzMg7l6E/Yw2VKTX7GdL6');
insert into users(email, first_name, last_name, password)VALUES ('alexKras06@gmail.com', 'alex', 'krasiuk', '$2a$10$0Ye41zYMioTuj8HuWzfQ1.5CPKmSXmkNkzMg7l6E/Yw2VKTX7GdL6');
insert into users(email, first_name, last_name, password)VALUES ('alexKras07@gmail.com', 'alex', 'krasiuk', '$2a$10$0Ye41zYMioTuj8HuWzfQ1.5CPKmSXmkNkzMg7l6E/Yw2VKTX7GdL6');

insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/1.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/2.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/3.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/4.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/5.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/6.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/7.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/8.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/9.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/10.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
insert into bulletins(header,author_user_id, date, image_path,text) values ('Lorem ipsum dol', '1', '2020-09-01 17:03:22', 'images/11.jpg','Vivamus ut elementum odio. Donec lacinia quis tellus et pulvinar. Integer commodo arcu vel quam sodales, non commodo diam tempor. Maecenas aliquet pellentesque sapien, eget luctus neque ornare eget. Suspendisse quis egestas arcu. Donec a semper neque. Praesent at sodales tellus.');
